# name: Developer Workflow


# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest


#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Install Node.js dependencies
#         run: |
#           npm install
#       - name: Run Unit tests
#         run: |
#           npm test
    