name: Workflow files for CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    env:
      VUE_APP_STRIPE_PUBLIC_KEY: ${{ secrets.VUE_APP_STRIPE_PUBLIC_KEY }}
      VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      # - name: Install OS level dependencies Nodejs v22.17.1
      #   run: actions/setup-node@v4
      #   with:
      #     node-version: "22.17.1"
      - name: Install Node.js dependencies
        run: |
          npm install
      - name: Start the application
        rum: npm run build
      # - name: Delete if the following pm2 process is running for this node-js application.
      #   run: |
      #     pm2 delete node-js || true
      # - name: start the application with pm2
      #   run: |
      #     pm2 start "npm run serve" --name="node-js"

