name: Workflow files for CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      # - name: Install OS level dependencies Nodejs v22.17.1
      #   run: actions/setup-node@v4
      #   with:
      #     node-version: "22.17.1"
      - name: Install Node.js dependencies
        run: | 
          npm install
      - name: Delete if any pm2 process is running for this node-js application
        run: | 
          pm2 delete node-js || true      
      - name: start the application with pm2
        run: | 
          pm2 start "npm run serve" --name="node-js"
