name: Workflow files for CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    env:
      VUE_APP_STRIPE_PUBLIC_KEY: ${{ secrets.VUE_APP_STRIPE_PUBLIC_KEY }}
      VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: |
          npm install
      - name: Build the application
        run: |
          npm run build

